---
- name: Deploy Maven Artifact
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: Copy JAR file
      copy: 
        src: "/var/lib/jenkins/workspace/HelloMaven-CI/target/HelloMaven-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/HelloMaven.jar"
