---
- name: Deploy Maven Artifact
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: Copy JAR file
      copy: 
        src: "/home/administratorq/.jenkins/workspace/HelloMaven-CII/target/MyFirstMavenApp-1.0-SNAPSHOT.jar"
        dest: /pt/deployment/HelloMaven.jar
